/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
export namespace Components {
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface EhsImageSection {
        "image": string;
    }
    interface EhsNavigation {
    }
    interface EhsSection {
        "color": string;
        "heading": any;
    }
    interface EhsSectionHeading {
        "theme": string;
    }
    interface EhsViewAbout {
    }
    interface EhsViewContact {
    }
    interface EhsViewPricing {
    }
}
declare global {
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLEhsImageSectionElement extends Components.EhsImageSection, HTMLStencilElement {
    }
    var HTMLEhsImageSectionElement: {
        prototype: HTMLEhsImageSectionElement;
        new (): HTMLEhsImageSectionElement;
    };
    interface HTMLEhsNavigationElement extends Components.EhsNavigation, HTMLStencilElement {
    }
    var HTMLEhsNavigationElement: {
        prototype: HTMLEhsNavigationElement;
        new (): HTMLEhsNavigationElement;
    };
    interface HTMLEhsSectionElement extends Components.EhsSection, HTMLStencilElement {
    }
    var HTMLEhsSectionElement: {
        prototype: HTMLEhsSectionElement;
        new (): HTMLEhsSectionElement;
    };
    interface HTMLEhsSectionHeadingElement extends Components.EhsSectionHeading, HTMLStencilElement {
    }
    var HTMLEhsSectionHeadingElement: {
        prototype: HTMLEhsSectionHeadingElement;
        new (): HTMLEhsSectionHeadingElement;
    };
    interface HTMLEhsViewAboutElement extends Components.EhsViewAbout, HTMLStencilElement {
    }
    var HTMLEhsViewAboutElement: {
        prototype: HTMLEhsViewAboutElement;
        new (): HTMLEhsViewAboutElement;
    };
    interface HTMLEhsViewContactElement extends Components.EhsViewContact, HTMLStencilElement {
    }
    var HTMLEhsViewContactElement: {
        prototype: HTMLEhsViewContactElement;
        new (): HTMLEhsViewContactElement;
    };
    interface HTMLEhsViewPricingElement extends Components.EhsViewPricing, HTMLStencilElement {
    }
    var HTMLEhsViewPricingElement: {
        prototype: HTMLEhsViewPricingElement;
        new (): HTMLEhsViewPricingElement;
    };
    interface HTMLElementTagNameMap {
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "ehs-image-section": HTMLEhsImageSectionElement;
        "ehs-navigation": HTMLEhsNavigationElement;
        "ehs-section": HTMLEhsSectionElement;
        "ehs-section-heading": HTMLEhsSectionHeadingElement;
        "ehs-view-about": HTMLEhsViewAboutElement;
        "ehs-view-contact": HTMLEhsViewContactElement;
        "ehs-view-pricing": HTMLEhsViewPricingElement;
    }
}
declare namespace LocalJSX {
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface EhsImageSection {
        "image"?: string;
    }
    interface EhsNavigation {
    }
    interface EhsSection {
        "color"?: string;
        "heading"?: any;
    }
    interface EhsSectionHeading {
        "theme"?: string;
    }
    interface EhsViewAbout {
    }
    interface EhsViewContact {
    }
    interface EhsViewPricing {
    }
    interface IntrinsicElements {
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "ehs-image-section": EhsImageSection;
        "ehs-navigation": EhsNavigation;
        "ehs-section": EhsSection;
        "ehs-section-heading": EhsSectionHeading;
        "ehs-view-about": EhsViewAbout;
        "ehs-view-contact": EhsViewContact;
        "ehs-view-pricing": EhsViewPricing;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "ehs-image-section": LocalJSX.EhsImageSection & JSXBase.HTMLAttributes<HTMLEhsImageSectionElement>;
            "ehs-navigation": LocalJSX.EhsNavigation & JSXBase.HTMLAttributes<HTMLEhsNavigationElement>;
            "ehs-section": LocalJSX.EhsSection & JSXBase.HTMLAttributes<HTMLEhsSectionElement>;
            "ehs-section-heading": LocalJSX.EhsSectionHeading & JSXBase.HTMLAttributes<HTMLEhsSectionHeadingElement>;
            "ehs-view-about": LocalJSX.EhsViewAbout & JSXBase.HTMLAttributes<HTMLEhsViewAboutElement>;
            "ehs-view-contact": LocalJSX.EhsViewContact & JSXBase.HTMLAttributes<HTMLEhsViewContactElement>;
            "ehs-view-pricing": LocalJSX.EhsViewPricing & JSXBase.HTMLAttributes<HTMLEhsViewPricingElement>;
        }
    }
}
